# Generated by Django 5.0.4 on 2025-02-08 16:00

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="LessonInfo",
            fields=[
                (
                    "lesson_num",
                    models.CharField(
                        db_column="lesson_id",
                        max_length=255,
                        primary_key=True,
                        serialize=False,
                        verbose_name="课程编号",
                    ),
                ),
                ("lesson_name", models.CharField(max_length=255, verbose_name="课程名称")),
                (
                    "notes",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="课程备注"
                    ),
                ),
            ],
            options={
                "verbose_name": "课程",
                "verbose_name_plural": "07-课程列表",
                "db_table": "lesson_info",
            },
        ),
        migrations.CreateModel(
            name="Policy",
            fields=[
                (
                    "policy_name",
                    models.CharField(
                        max_length=255,
                        primary_key=True,
                        serialize=False,
                        verbose_name="政策名称",
                    ),
                ),
                ("content", models.TextField(verbose_name="政策内容")),
                (
                    "publish_time",
                    models.DateTimeField(
                        blank=True,
                        default=django.utils.timezone.now,
                        null=True,
                        verbose_name="发布时间",
                    ),
                ),
            ],
            options={
                "verbose_name": "政策",
                "verbose_name_plural": "00-政策列表",
                "db_table": "policy",
            },
        ),
        migrations.CreateModel(
            name="Semester",
            fields=[
                (
                    "semester_name",
                    models.CharField(
                        max_length=255,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name="学期名称",
                    ),
                ),
                (
                    "start_date",
                    models.DateField(blank=True, null=True, verbose_name="开始日期"),
                ),
                (
                    "end_date",
                    models.DateField(blank=True, null=True, verbose_name="结束日期"),
                ),
                (
                    "notes",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="备注"
                    ),
                ),
            ],
            options={
                "verbose_name": "学期",
                "verbose_name_plural": "05-学期列表",
                "db_table": "semester",
            },
        ),
        migrations.CreateModel(
            name="UserInfo",
            fields=[
                (
                    "uid",
                    models.CharField(
                        max_length=32,
                        primary_key=True,
                        serialize=False,
                        verbose_name="用户ID",
                    ),
                ),
                ("username", models.CharField(max_length=255, verbose_name="用户名")),
                (
                    "gender",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="性别"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=255, null=True, verbose_name="邮箱"
                    ),
                ),
                (
                    "birthday",
                    models.DateField(blank=True, null=True, verbose_name="生日"),
                ),
                (
                    "notes",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="备注"
                    ),
                ),
            ],
            options={
                "verbose_name": "用户信息",
                "verbose_name_plural": "01-用户信息列表",
                "db_table": "user_info",
            },
        ),
        migrations.CreateModel(
            name="LessonPrerequisite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "notes",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="备注"
                    ),
                ),
                (
                    "from_lesson",
                    models.ForeignKey(
                        db_column="from_lesson",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="from_lessons",
                        to="smart_class.lessoninfo",
                        verbose_name="课程",
                    ),
                ),
                (
                    "to_lesson",
                    models.ForeignKey(
                        db_column="to_lesson",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="to_lessons",
                        to="smart_class.lessoninfo",
                        verbose_name="前序课程",
                    ),
                ),
            ],
            options={
                "verbose_name": "课程前序关系",
                "verbose_name_plural": "08-课程前序关系列表",
                "db_table": "lesson_prerequisite",
            },
        ),
        migrations.CreateModel(
            name="TeacherDetail",
            fields=[
                (
                    "uid",
                    models.OneToOneField(
                        db_column="uid",
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="smart_class.userinfo",
                        verbose_name="用户ID",
                    ),
                ),
                ("teacher_num", models.CharField(max_length=255, verbose_name="教师编号")),
                (
                    "notes",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="教师备注"
                    ),
                ),
            ],
            options={
                "verbose_name": "教师详情",
                "verbose_name_plural": "04-教师详情列表",
                "db_table": "teacher_detail",
            },
        ),
        migrations.CreateModel(
            name="UserAuth",
            fields=[
                (
                    "uid",
                    models.OneToOneField(
                        db_column="uid",
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="smart_class.userinfo",
                        verbose_name="用户ID",
                    ),
                ),
                (
                    "open_id",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="开放ID"
                    ),
                ),
                ("password", models.CharField(max_length=255, verbose_name="密码")),
            ],
            options={
                "verbose_name": "用户凭证",
                "verbose_name_plural": "02-用户凭证列表",
                "db_table": "user_auth",
            },
        ),
        migrations.CreateModel(
            name="Class",
            fields=[
                (
                    "class_name",
                    models.CharField(
                        max_length=255,
                        primary_key=True,
                        serialize=False,
                        verbose_name="班级名称",
                    ),
                ),
                (
                    "notes",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="备注"
                    ),
                ),
                (
                    "teacher_uid",
                    models.ForeignKey(
                        blank=True,
                        db_column="teacher_uid",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="teacher_classes",
                        to="smart_class.userinfo",
                        verbose_name="班主任",
                    ),
                ),
            ],
            options={
                "verbose_name": "班级",
                "verbose_name_plural": "06-班级列表",
                "db_table": "class",
            },
        ),
        migrations.CreateModel(
            name="Announcement",
            fields=[
                (
                    "announcement_name",
                    models.CharField(
                        max_length=255,
                        primary_key=True,
                        serialize=False,
                        verbose_name="公告名称",
                    ),
                ),
                (
                    "publish_time",
                    models.DateTimeField(
                        blank=True,
                        default=django.utils.timezone.now,
                        null=True,
                        verbose_name="发布时间",
                    ),
                ),
                ("content", models.TextField(verbose_name="公告内容")),
                (
                    "class_name",
                    models.ForeignKey(
                        db_column="class_name",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="smart_class.class",
                        verbose_name="班级",
                    ),
                ),
                (
                    "publisher",
                    models.ForeignKey(
                        db_column="publisher_uid",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="smart_class.userinfo",
                        verbose_name="发布人",
                    ),
                ),
            ],
            options={
                "verbose_name": "公告",
                "verbose_name_plural": "10-班级公告列表",
                "db_table": "announcement",
            },
        ),
        migrations.CreateModel(
            name="StuDetail",
            fields=[
                (
                    "uid",
                    models.OneToOneField(
                        db_column="uid",
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="smart_class.userinfo",
                        verbose_name="用户ID",
                    ),
                ),
                ("stu_num", models.CharField(max_length=255, verbose_name="学号")),
                (
                    "major",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="专业"
                    ),
                ),
                (
                    "stu_position",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="职务"
                    ),
                ),
                (
                    "notes",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="备注"
                    ),
                ),
                (
                    "class_name",
                    models.ForeignKey(
                        blank=True,
                        db_column="stu_class",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="smart_class.class",
                        verbose_name="班级",
                    ),
                ),
            ],
            options={
                "verbose_name": "学生详情",
                "verbose_name_plural": "03-学生详情列表",
                "db_table": "stu_detail",
            },
        ),
        migrations.CreateModel(
            name="StuGrade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "grade",
                    models.DecimalField(
                        decimal_places=2, max_digits=5, verbose_name="成绩"
                    ),
                ),
                (
                    "notes",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="备注"
                    ),
                ),
                (
                    "lesson_num",
                    models.ForeignKey(
                        db_column="lesson_num",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="smart_class.lessoninfo",
                        verbose_name="课程编号",
                    ),
                ),
                (
                    "semester",
                    models.ForeignKey(
                        db_column="semester",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="smart_class.semester",
                        verbose_name="学期",
                    ),
                ),
                (
                    "uid",
                    models.ForeignKey(
                        db_column="uid",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="smart_class.userinfo",
                        verbose_name="用户ID",
                    ),
                ),
            ],
            options={
                "verbose_name": "学生成绩",
                "verbose_name_plural": "09-学生成绩列表",
                "db_table": "stu_grade",
                "unique_together": {("uid", "lesson_num", "semester")},
            },
        ),
    ]
