# Generated by Django 5.0.4 on 2025-02-08 15:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("smart_class", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="studetail",
            name="stu_leader",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="职务"
            ),
        ),
        migrations.AlterField(
            model_name="lessonprerequisite",
            name="from_lesson",
            field=models.ForeignKey(
                db_column="from_lesson",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="from_lessons",
                to="smart_class.lessoninfo",
                verbose_name="课程",
            ),
        ),
        migrations.AlterField(
            model_name="lessonprerequisite",
            name="to_lesson",
            field=models.ForeignKey(
                db_column="to_lesson",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="to_lessons",
                to="smart_class.lessoninfo",
                verbose_name="前序课程",
            ),
        ),
        migrations.AlterField(
            model_name="stugrade",
            name="lesson_id",
            field=models.ForeignKey(
                db_column="lesson_id",
                on_delete=django.db.models.deletion.CASCADE,
                to="smart_class.lessoninfo",
                verbose_name="课程编号",
            ),
        ),
        migrations.AlterField(
            model_name="stugrade",
            name="semester",
            field=models.ForeignKey(
                db_column="semester",
                on_delete=django.db.models.deletion.CASCADE,
                to="smart_class.semester",
                verbose_name="学期",
            ),
        ),
        migrations.AlterField(
            model_name="stugrade",
            name="uid",
            field=models.ForeignKey(
                db_column="uid",
                on_delete=django.db.models.deletion.CASCADE,
                to="smart_class.userinfo",
                verbose_name="用户ID",
            ),
        ),
        migrations.DeleteModel(
            name="ClassLeaderDetail",
        ),
    ]
