# Generated by Django 5.0.4 on 2025-02-08 16:24

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("smart_class", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "message_id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="消息ID"
                    ),
                ),
                ("content", models.TextField(verbose_name="消息内容")),
                (
                    "send_time",
                    models.DateTimeField(
                        blank=True,
                        default=django.utils.timezone.now,
                        null=True,
                        verbose_name="发送时间",
                    ),
                ),
                (
                    "is_read",
                    models.BooleanField(
                        blank=True, default=False, null=True, verbose_name="是否已读"
                    ),
                ),
                (
                    "receiver",
                    models.ForeignKey(
                        db_column="receiver_uid",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="received_messages",
                        to="smart_class.userinfo",
                        verbose_name="接收者",
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        db_column="sender_uid",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sent_messages",
                        to="smart_class.userinfo",
                        verbose_name="发送者",
                    ),
                ),
            ],
            options={
                "verbose_name": "站内消息",
                "verbose_name_plural": "11-站内消息列表",
                "db_table": "message",
            },
        ),
    ]
