# Generated by Django 5.0.4 on 2025-02-08 20:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("smart_class", "0002_message"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="announcement",
            options={"verbose_name": "公告", "verbose_name_plural": "10-班级公告"},
        ),
        migrations.AlterModelOptions(
            name="class",
            options={"verbose_name": "班级", "verbose_name_plural": "06-班级"},
        ),
        migrations.AlterModelOptions(
            name="lessoninfo",
            options={"verbose_name": "课程", "verbose_name_plural": "07-课程"},
        ),
        migrations.AlterModelOptions(
            name="lessonprerequisite",
            options={"verbose_name": "课程前序关系", "verbose_name_plural": "08-课程关系"},
        ),
        migrations.AlterModelOptions(
            name="message",
            options={"verbose_name": "站内消息", "verbose_name_plural": "11-站内消息"},
        ),
        migrations.AlterModelOptions(
            name="policy",
            options={"verbose_name": "政策", "verbose_name_plural": "00-政策"},
        ),
        migrations.AlterModelOptions(
            name="semester",
            options={"verbose_name": "学期", "verbose_name_plural": "05-学期"},
        ),
        migrations.AlterModelOptions(
            name="studetail",
            options={"verbose_name": "学生详情", "verbose_name_plural": "03-学生详情"},
        ),
        migrations.AlterModelOptions(
            name="stugrade",
            options={"verbose_name": "学生成绩", "verbose_name_plural": "09-学生成绩"},
        ),
        migrations.AlterModelOptions(
            name="teacherdetail",
            options={"verbose_name": "教师详情", "verbose_name_plural": "04-教师详情"},
        ),
        migrations.AlterModelOptions(
            name="userauth",
            options={"verbose_name": "用户凭证", "verbose_name_plural": "02-用户凭证"},
        ),
        migrations.AlterModelOptions(
            name="userinfo",
            options={"verbose_name": "用户信息", "verbose_name_plural": "01-用户信息"},
        ),
        migrations.AlterField(
            model_name="studetail",
            name="class_name",
            field=models.ForeignKey(
                blank=True,
                db_column="class_name",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="smart_class.class",
                verbose_name="班级",
            ),
        ),
    ]
