# Generated by Django 5.0.4 on 2025-02-08 15:36

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("smart_class", "0002_studetail_stu_leader_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Policy",
            fields=[
                (
                    "policy_name",
                    models.CharField(
                        max_length=255,
                        primary_key=True,
                        serialize=False,
                        verbose_name="政策名称",
                    ),
                ),
                ("content", models.TextField(verbose_name="政策内容")),
                (
                    "publish_time",
                    models.DateTimeField(
                        blank=True,
                        default=django.utils.timezone.now,
                        null=True,
                        verbose_name="发布时间",
                    ),
                ),
            ],
            options={
                "verbose_name": "政策",
                "verbose_name_plural": "11-政策列表",
                "db_table": "policy",
            },
        ),
        migrations.AlterModelOptions(
            name="semester",
            options={"verbose_name": "学期", "verbose_name_plural": "05-学期列表"},
        ),
        migrations.CreateModel(
            name="Announcement",
            fields=[
                (
                    "announcement_name",
                    models.CharField(
                        max_length=255,
                        primary_key=True,
                        serialize=False,
                        verbose_name="公告名称",
                    ),
                ),
                (
                    "publish_time",
                    models.DateTimeField(
                        blank=True,
                        default=django.utils.timezone.now,
                        null=True,
                        verbose_name="发布时间",
                    ),
                ),
                ("content", models.TextField(verbose_name="公告内容")),
                (
                    "class_name",
                    models.ForeignKey(
                        db_column="class_name",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="smart_class.class",
                        verbose_name="班级",
                    ),
                ),
                (
                    "publisher",
                    models.ForeignKey(
                        db_column="publisher_uid",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="smart_class.userinfo",
                        verbose_name="发布人",
                    ),
                ),
            ],
            options={
                "verbose_name": "公告",
                "verbose_name_plural": "10-公告列表",
                "db_table": "announcement",
            },
        ),
    ]
