# Generated by Django 5.0.4 on 2025-02-08 22:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("smart_class", "0003_alter_announcement_options_alter_class_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userauth",
            name="login_time",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="允许登录时间"
            ),
        ),
        migrations.AddField(
            model_name="userauth",
            name="retry_count",
            field=models.IntegerField(default=0, verbose_name="重试次数"),
        ),
    ]
