# Generated by Django 5.0.4 on 2025-02-13 14:20

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("smart_class", "0004_userauth_login_time_userauth_retry_count"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lessoninfo",
            name="lesson_num",
            field=models.CharField(
                db_column="lesson_num",
                max_length=255,
                primary_key=True,
                serialize=False,
                verbose_name="课程编号",
            ),
        ),
        migrations.AlterField(
            model_name="stugrade",
            name="lesson_num",
            field=models.ForeignKey(
                blank=True,
                db_column="lesson_num",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="smart_class.lessoninfo",
                verbose_name="课程编号",
            ),
        ),
        migrations.AlterField(
            model_name="userauth",
            name="login_time",
            field=models.DateTimeField(
                default=datetime.datetime.utcnow, verbose_name="允许登录时间(utc)"
            ),
        ),
    ]
